# Generated by Django 3.0.6 on 2020-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('size', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
