# Generated by Django 3.0.6 on 2020-07-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200714_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cat_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
