# Generated by Django 3.0.6 on 2020-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'demo',
            },
        ),
    ]
