# Generated by Django 3.0.6 on 2020-07-09 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demomodel_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='designation',
            field=models.TextField(default='', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets allowed.')]),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabets allowed.')]),
        ),
    ]
